dataset:
  batch_size: 32

train:
  device: "cuda:0"
  lr: 0.001
  weight_decay: 0.0001
  epochs: 100
  early_stop_patience: 15
  early_stop_min_delta: 0.005

model:
  task_name: 'classification'
  seq_len: 200                 
  enc_in: 22                   
  num_class: 2                 

  pred_len: 0                  
  label_len: 0                 
  
  # TimesNet 参数
  e_layers: 2                  # TimesBlock 层数
  d_model: 64                  
  d_ff: 64                     
  top_k: 5                     # FFT 提取的最高频周期个数
  num_kernels: 6               # Inception block 内部卷积核数量
  
  # Embedding 参数
  embed: 'timeF'
  freq: 'h'
  dropout: 0.1
  c_out: 2                     